server:
  port: 8080

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
  server:
    port: 5000
telegram:
  bot:
    username: "@TicketsSuggestionBot"
    botToken: 5502365793:AAF7QMf08TjBOsUKs5PHyhG5ELiIY4sTmlY
    webHookPath: https://7cac-5-197-192-120.eu.ngrok.io/
    telegramUrl: https://api.telegram.org/bot
    botPath: webhook

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_DATABASE}/${POSTGRES_PORT}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml