server:
  port: 8081

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
  server:
    port: 5001
telegram:
  bot:
    username: "@TicketsSuggestionBot"
    botToken: 5502365793:AAF7QMf08TjBOsUKs5PHyhG5ELiIY4sTmlY
    webHookPath: https://7cac-5-197-192-120.eu.ngrok.io/
    telegramUrl: https://api.telegram.org/bot
    botPath: webhook
