apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-telegram-bot
spec:
  replicas: 3
  selector:
    matchLabels:
      component: telegram-bot
  template:
    metadata:
      labels:
        component: telegram-bot
    spec:
      containers:
        - name: client
          image: container-image
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 5000
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 5000
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_HOST
              value: postgres-cluster-ip-service
            - name: POSTGRES_PORT
              value: '5432'
            - name: POSTGRES_DATABASE
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: ms-telegram-bot-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: telegram-bot
  ports:
    - port:  8080
      targetPort: 80