name: "Validate and Deploy k8s-ingress"

on:
  push:
    paths:
      - '.github/k8s-ingress_cicd.yml'
      - 'k8s-ingress/**'
env:
  GKE_CLUSTER: cluster-1
  GKE_ZONE: europe-west1-b

jobs:
  validate-infra:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Setup gcloud CLI"
        uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - name: "Get the GKE credentials for validating to the cluster"
        uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      - name: "Validate ingress"
        working-directory: "k8s-ingress"
        run: |
          pwd
          echo "Validate k8s-ingress.yml file"
          kubectl apply -f k8s-ingress.yml --dry-run='client'
        shell: bash

  deploy:
    if: ${{ github.ref_name == 'main' }}
    needs: [validate-infra ]
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Setup gcloud CLI"
        uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - name: "Get the GKE credentials for validating to the cluster"
        uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      - name: "Apply to Kubernetes"
        working-directory: "k8s-ingress"
        run: |
          echo "Deploying to cluster  ..."
          kubectl apply -f k8s-ingress.yml
        shell: bash